name: export-secrets-action
author: koyashiro <develop@koyashiro.net>
description: Export GitHub Actions secrets as environment variables
inputs:
  secrets:
    description: JSON representation of secrets
    required: true
  downcase-tf-var:
    description: Set this option if you want to downcase the secrets starting with `TF_VAR_`
    required: false
  downcase-tf-token:
    description: Set this option if you want to downcase the secrets starting with `TF_TOKEN_`
    required: false
runs:
  using: node20
  main: dist/index.js
